version: "3"
services:
  radicale:
    image: tomsquest/docker-radicale
    ports:
      - "5232:5232"
    volumes:
      - radicale-data:/data
      - radicale-config:/config
    environment:
      - RADICALE_CONFIG=/config/radicale-config

volumes:
  radicale-data:
  radicale-config:
